VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /SPOJ
    COPY SPOJ .
    RUN g++ -O3 -static -o wstp wstp.cpp
    SAVE ARTIFACT wstp /bin/
    SAVE ARTIFACT sbstr1 /programs/
    SAVE ARTIFACT sbstr1.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wstp"]
    SAVE IMAGE wspace-corpus/cpp/codesiiita-spoj
