VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev perl
    WORKDIR /ws
    COPY ws .
    RUN perl parsegen.pl parse.def > gencode.c && \
        gcc -O3 -g -static -o wspace parse.c vm.c wspace.c
    SAVE ARTIFACT wspace /bin/
    SAVE ARTIFACT examples/*.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/c/hogelog
