VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /whitespace-rs
    COPY whitespace-rs .
    # RUN cargo test
    RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/compiler /bin/
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/interpreter /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/compiler"]
    SAVE IMAGE wspace-corpus/rust/keirua
