VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /WhiteSpace-Interpreter
    COPY WhiteSpace-Interpreter .
    RUN javac -d bin *.java && \
        jar -cfe WhiteSpace.jar Test -C bin .
    SAVE ARTIFACT WhiteSpace.jar /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /WhiteSpace-Interpreter
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/WhiteSpace.jar"]
    SAVE IMAGE wspace-corpus/java/rahulkp
