VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make clang g++
    WORKDIR /wsInt
    COPY wsInt .
    RUN make CPPFLAGS='-O3 -static'
    RUN clang++ -O3 -o bin/ParserTest tests/ParserTest.cpp src/parser/*.o
    RUN bin/ParserTest
    SAVE ARTIFACT bin/wsInt /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wsInt"]
    SAVE IMAGE wspace-corpus/cpp/dpohanlon-wsint
