VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /wsInt
    COPY wsInt .
    RUN mkdir bin && \
        g++ -O3 -static -o bin/wsInt src/*.cpp src/parser/*.cpp src/vm/*.cpp && \
        g++ -g -o bin/ParserTest tests/ParserTest.cpp src/parser/*.cpp
    RUN bin/ParserTest
    SAVE ARTIFACT bin/wsInt /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wsInt"]
    SAVE IMAGE wspace-corpus/cpp/dpohanlon-wsint
