VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace
    COPY whitespace .
    RUN g++ -O3 -static -o white main.cpp
    SAVE ARTIFACT white /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/white"]
    SAVE IMAGE wspace-corpus/cpp/keirua-white
