VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /lalrpop
    COPY lalrpop .
    RUN cargo test --package whitespace && \
        RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu --package whitespace
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/whitespace /bin/
    SAVE ARTIFACT doc/whitespace/hello.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/rust/lalrpop
