VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev
    WORKDIR /whitespace
    COPY whitespace .
    RUN gcc -O3 -g -static -o whitespace src/*.c
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/c/censoredusername
