VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev
    WORKDIR /Whitespace
    COPY Whitespace .
    RUN gcc -O3 -g -static -o white y.tab.c lex.yy.c
    SAVE ARTIFACT white /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/white"]
    SAVE IMAGE wspace-corpus/c/sandeep023
