VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /whitenote
    COPY whitenote .
    WORKDIR /whitenote/wspace/cmd/wspace
    RUN go test && \
        CGO_ENABLED=0 go build
    SAVE ARTIFACT wspace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/go/makiuchid-whitenote
