VERSION 0.8

build:
    FROM mono
    WORKDIR /Whitespace-Interpreter
    COPY Whitespace-Interpreter .
    RUN mcs -optimize -out:WhitespaceInterpreter.exe WhitespaceInterpreter/*.cs
    SAVE ARTIFACT WhitespaceInterpreter.exe /bin/

docker:
    FROM mono:slim
    WORKDIR /Whitespace-Interpreter
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/WhitespaceInterpreter.exe"]
    SAVE IMAGE wspace-corpus/csharp/denislabrecque
