VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /whitespace-interpreter
    COPY misc-proj/java/whitespace-interpreter .
    RUN javac -d bin Whitespace.java && \
        jar -cfe whitespace.jar Whitespace -C bin .
    COPY misc-proj/java/whitespace-polyglot/HelloWorld.java .
    SAVE ARTIFACT whitespace.jar /bin/
    SAVE ARTIFACT HelloWorld.java /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whitespace-interpreter
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespace.jar"]
    SAVE IMAGE wspace-corpus/java/thatguy977
