VERSION 0.8

build:
    FROM alpine
    WORKDIR /Whitespace
    COPY Whitespace .
    RUN set -e \
        \
        apk add --no-cache gcc g++ \
        gcc -O3 -static -o wlang whitespace.c \
        g++ -O3 -static -o whitespacecpp whitespace.cpp
    SAVE ARTIFACT wlang /bin/
    SAVE ARTIFACT whitespacecpp /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wlang"]
    SAVE IMAGE wspace-corpus/c/zackeua
