VERSION 0.8

build:
    FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.1_12_1.9.8_3.3.1
    WORKDIR /WhitespaceEvaluator
    COPY WhitespaceEvaluator .
    RUN sbt test assembly
    SAVE ARTIFACT target/scala-3.3.1/WhitespaceEvaluator-assembly-0.3.jar WhitespaceEvaluator.jar

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /WhitespaceEvaluator
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/WhitespaceEvaluator.jar"]
    SAVE IMAGE wspace-corpus/scala/andreal2000
