VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    ENTRYPOINT ["python", "whitespace_interpreter.py"]
    SAVE IMAGE wspace-corpus/python/adapap
