VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /go-whitespace
    COPY go-whitespace .
    RUN CGO_ENABLED=0 go build -o go-whitespace ./src
    SAVE ARTIFACT go-whitespace /bin/
    SAVE ARTIFACT samples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/go-whitespace"]
    SAVE IMAGE wspace-corpus/go/technohippy
