VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache bash g++
    WORKDIR /whitespace
    COPY whitespace .
    RUN bash build.sh release wspace
    SAVE ARTIFACT wspace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/cpp/shadowmitia
