VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace
    COPY whitespace .
    RUN g++ -std=c++20 -O3 -static -fopenmp -foptimize-sibling-calls src/main.cpp -o wspace
    SAVE ARTIFACT wspace /bin/
    SAVE ARTIFACT examples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/cpp/shadowmitia
