VERSION 0.8

build:
    FROM ocaml/opam:debian
    USER root
    RUN apt-get update && \
        apt-get install -y --no-install-recommends bats && \
        rm -rf /var/lib/apt/lists/*
    USER opam
    RUN opam install dune menhir ounit2
    COPY --chown=opam spacebar /home/opam/spacebar
    WORKDIR /home/opam/spacebar
    RUN eval $(opam env) && \
        dune runtest && \
        dune build --profile release
    RUN sed -i 's,$(git rev-parse --show-toplevel),.,' test/functional.sh
    # TODO: Needs wspace binary:
    # RUN test/functional.sh
    SAVE ARTIFACT opam/spacebar/_build/default/spacebar.exe /bin/
    SAVE ARTIFACT test/*.c /

docker:
    FROM debian
    WORKDIR /spacebar
    COPY +build/ .
    ENTRYPOINT ["bin/spacebar.exe"]
    SAVE IMAGE wspace-corpus/ocaml/progbits-spacebar
