VERSION 0.8

build:
    FROM ocaml/opam:alpine
    USER root
    RUN apk add --no-cache bats patch
    USER opam
    RUN opam install dune menhir ounit2
    COPY --chown=opam spacebar static.patch /home/opam/spacebar
    WORKDIR /home/opam/spacebar
    RUN patch -p1 -i static.patch
    RUN eval $(opam env) && \
        dune runtest && \
        dune build --profile release
    RUN sed -i 's,$(git rev-parse --show-toplevel),.,' test/functional.sh
    # TODO: Needs wspace binary:
    # RUN test/functional.sh
    SAVE ARTIFACT _build/default/spacebar.exe /bin/
    SAVE ARTIFACT test/*.c /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/spacebar.exe"]
    SAVE IMAGE wspace-corpus/ocaml/progbits-spacebar
