VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /wseditor
    COPY wseditor .
    RUN javac -d bin $(find src -name '*.java') && \
        jar -cfe wseditor.jar wseditor.Main -C bin .
    SAVE ARTIFACT wseditor.jar /bin/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /wseditor
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/wseditor.jar"]
    SAVE IMAGE wspace-corpus/java/yuukiaria-wseditor
