VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make gcc musl-dev
    WORKDIR /satan
    COPY satan .
    RUN make
    SAVE ARTIFACT satan /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/satan"]
    SAVE IMAGE wspace-corpus/c/threeifbywhiskey-satan
