VERSION 0.8

build:
    FROM maven:3-eclipse-temurin-21-alpine
    WORKDIR /whitespace-coder
    COPY whitespace-coder .
    RUN mvn -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 package && \
        java -cp target/whitespace-coder-1.0-SNAPSHOT.jar Factorial && \
        java -cp target/whitespace-coder-1.0-SNAPSHOT.jar FCTRIZE && \
        java -cp target/whitespace-coder-1.0-SNAPSHOT.jar HelloWorld
    SAVE ARTIFACT target/whitespace-coder-1.0-SNAPSHOT.jar /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whitespace-coder
    COPY +build/ .
    ENTRYPOINT ["java", "-cp", "bin/whitespace-coder-1.0-SNAPSHOT.jar"]
    SAVE IMAGE wspace-corpus/java/praveenvaka-coder
