VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN g++ -std=c++11 -O3 -static -o whitespace *.cpp
    SAVE ARTIFACT whitespace /bin/
    SAVE ARTIFACT *.ws /programs/
    SAVE ARTIFACT *.txt /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/cpp/timvandermeij
