VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN make
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/cpp/timvandermeij
