VERSION 0.8

docker:
    FROM python:3-alpine
    RUN pip install whitespace
    WORKDIR /hohoho
    COPY hohoho .
    ENTRYPOINT ["python", "-m", "hohoho"]
    SAVE IMAGE wspace-corpus/python/freyamade-hohoho
