VERSION 0.8

build:
    FROM alpine
    WORKDIR /vvhitespace
    COPY vvhitespace .
    RUN set -e \
        \
        apk add --no-cache gcc musl-dev python3 \
        \
        gcc -O3 -g -static -std=c99 -o vvc vv_compiler.c \
        gcc -O3 -g -static -std=c99 -o vvi vv_interpreter.c \
        (cd tests && python3 vv_test.py) \
        (cd stdlib_tests && python3 vv_test.py)
    SAVE ARTIFACT vvc /bin/
    SAVE ARTIFACT vvi /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/vvi"]
    SAVE IMAGE wspace-corpus/c/subgeniuskitty-vvhitespace
