VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /whasm
    COPY whasm .
    RUN javac -d bin WhAsm.java && \
        jar -cfe whasm.jar WhAsm -C bin .
    SAVE ARTIFACT whasm.jar /bin/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whasm
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whasm.jar"]
    SAVE IMAGE wspace-corpus/java/matou-whasm
