VERSION 0.8

docker:
    FROM node:alpine
    WORKDIR /GrassMudMonkey
    COPY GrassMudMonkey cli.js ./
    RUN cat cli.js >> grassmudmonkey.js
    ENTRYPOINT ["node", "grassmudmonkey"]
    SAVE IMAGE wspace-corpus/javascript/dexteryy-grassmudmonkey
