VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitespace-Interpreter-C-
    COPY Whitespace-Interpreter-C- .
    RUN g++ -O3 -static -o space space.cpp
    SAVE ARTIFACT space /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/space"]
    SAVE IMAGE wspace-corpus/cpp/sudheesh4
