VERSION 0.8

build:
    FROM mono
    WORKDIR /WhitespaceAssembler
    COPY WhitespaceAssembler .
    RUN msbuild -p:Configuration=Release
    SAVE ARTIFACT bin/Release/WhitespaceAssembler.exe /bin/
    SAVE ARTIFACT examples /programs

docker:
    FROM mono:slim
    WORKDIR /WhitespaceAssembler
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/WhitespaceAssembler.exe"]
    SAVE IMAGE wspace-corpus/csharp/littlebughunter-assembler
