VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitepp
    COPY Whitepp .
    RUN mkdir bin && \
        g++ -std=gnu++14 -O3 -static -I include -o bin/White++ src/*.cpp
    SAVE ARTIFACT bin/White++ /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/White++"]
    SAVE IMAGE wspace-corpus/cpp/marcellippmann-whitepp
