VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /Whitepp
    COPY Whitepp .
    RUN make
    SAVE ARTIFACT bin/White++ /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/White++"]
    SAVE IMAGE wspace-corpus/cpp/marcellippmann-whitepp
