VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev
    WORKDIR /whitespace-php
    COPY whitespace-php .
    RUN gcc -O3 -static -o whitespace *.c
    SAVE ARTIFACT whitespace /bin/
    SAVE ARTIFACT samples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/php/nobody1986
