VERSION 0.8

build:
    FROM haskell:8-slim-buster
    RUN cabal update
    RUN cabal install -j idris
    WORKDIR /WS-idr
    COPY WS-idr .
    RUN idris --build wspace.ipkg
    SAVE ARTIFACT wspace /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM debian:buster-slim
    WORKDIR /WS-idr
    COPY +build/ .
    ENTRYPOINT ["bin/wspace"]
    SAVE IMAGE wspace-corpus/idris/edwinb-ws-idr
