VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make gcc musl-dev
    WORKDIR /wspacegen
    COPY wspacegen .
    RUN make CFLAGS='-O3 -g -static'
    SAVE ARTIFACT wspacegen /bin/
    SAVE ARTIFACT wsdbg /bin/
    SAVE ARTIFACT wsi /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspacegen"]
    SAVE IMAGE wspace-corpus/c/stellwag-wspacegen
