VERSION 0.8

docker:
    FROM perl
    RUN cpanm Algorithm::Combinatorics File::Basename Parse::Token::Lite String::Unescape Tie::RegexpHash
    WORKDIR /wsm2ws
    COPY wsm2ws .
    ENTRYPOINT ["perl", "wsm2ws.pl"]
    SAVE IMAGE wspace-corpus/perl/ephphatha-wsm2ws
