VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /WhiteSpaceInterpreter
    COPY WhiteSpaceInterpreter .
    RUN javac -d bin src/whitespace/whitespace.java && \
        jar -cfe whitespace.jar whitespace.whitespace -C bin .
    SAVE ARTIFACT whitespace.jar /bin/
    SAVE ARTIFACT src/fichero.bin /

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /WhiteSpaceInterpreter
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespace.jar"]
    SAVE IMAGE wspace-corpus/java/eiauniversity
