VERSION 0.8

IMPORT ./thaliaarchi-wsjq AS jq-thaliaarchi-wsjq

build:
    FROM scratch
    BUILD jq-thaliaarchi-wsjq+build
    WORKDIR /corpus/jq
    COPY jq-thaliaarchi-wsjq+build/ thaliaarchi-wsjq/
    SAVE ARTIFACT /corpus /corpus

docker:
    FROM alpine
    WORKDIR /corpus/jq
    COPY +build/ /
    SAVE IMAGE wspace-corpus/jq

docker-all:
    BUILD +docker
    BUILD jq-thaliaarchi-wsjq+docker
