VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitespace
    COPY Whitespace .
    RUN g++ -O3 -std=c++11 -static -o wsi whitespace/main.cpp
    SAVE ARTIFACT wsi /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wsi"]
    SAVE IMAGE wspace-corpus/cpp/abcsharp
