VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make crystal
    WORKDIR /spiceweight
    COPY spiceweight .
    RUN make
    SAVE ARTIFACT spwt /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/spwt"]
    SAVE IMAGE wspace-corpus/crystal/collidedscope-spiceweight
