VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make crystal
    WORKDIR /spiceweight
    COPY spiceweight .
    RUN crystal build --release --static -o spwt spiceweight.cr
    SAVE ARTIFACT spwt /bin/
    SAVE ARTIFACT spec/fixtures /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/spwt"]
    SAVE IMAGE wspace-corpus/crystal/collidedscope-spiceweight
