VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /WhitespaceInterpreter
    COPY WhitespaceInterpreter .
    RUN rustc -C target-feature=+crt-static -o wi whitespace_interpreter.rs
    SAVE ARTIFACT wi /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wi"]
    SAVE IMAGE wspace-corpus/rust/kaisugi
