VERSION 0.8

build:
    FROM mono
    WORKDIR /Esoteric-Code-Interpreter
    COPY Esoteric-Code-Interpreter .
    RUN msbuild -p:Configuration=Release\;AssemblyName=EsotericCodeInterpreter
    SAVE ARTIFACT bin/Release/EsotericCodeInterpreter.exe /bin/

docker:
    FROM mono:slim
    WORKDIR /Esoteric-Code-Interpreter
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/EsotericCodeInterpreter.exe"]
    SAVE IMAGE wspace-corpus/csharp/rolisoft-esoteric
