VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace-jit
    COPY whitespace-jit .
    RUN g++ -std=c++17 -O3 -static -o compile *.cc
    SAVE ARTIFACT compile /bin/
    SAVE ARTIFACT programs /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/compile"]
    SAVE IMAGE wspace-corpus/cpp/drebelsky-jit
