VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /whitespace-jit
    COPY whitespace-jit .
    RUN make CXXFLAGS='-O3 -static'
    SAVE ARTIFACT compile /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/compile"]
    SAVE IMAGE wspace-corpus/cpp/drebelsky-jit
