VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /yspace
    COPY yspace .
    RUN rustup override set nightly && \
        cargo test && \
        RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/yspace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/yspace"]
    SAVE IMAGE wspace-corpus/rust/thaliaarchi-yspace
