VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /wspace
    COPY wspace .
    RUN g++ -O3 -static -o wspace wspace.cpp && \
        g++ -O3 -static -o assembler assembler.cpp
    SAVE ARTIFACT wspace /bin/
    SAVE ARTIFACT assembler /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/cpp/pavel987
