VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /wspace
    COPY wspace .
    RUN make
    SAVE ARTIFACT wspace /bin/
    SAVE ARTIFACT assembler /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspace"]
    SAVE IMAGE wspace-corpus/cpp/pavel987
