VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /whitespace
    COPY whitespace .
    RUN go mod init github.com/kinu/whitespace && \
        CGO_ENABLED=0 go build
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/go/kinu
