VERSION 0.8

build:
    FROM alpine
    WORKDIR /wsdebug
    RUN set -e \
        \
        apk add --no-cache curl make gcc g++ gmp-dev readline-dev \
        # wsdebug-0.1.tar.gz has ./configure, but not git \
        curl https://master.dl.sourceforge.net/project/wsdebug.berlios/wsdebug-0.1.tar.gz?viasf=1 | gunzip | tar xf - --strip-components 1 \
        ./configure \
        make CFLAGS='-O3 -g -static'
    SAVE ARTIFACT wsdebug /bin/
    SAVE ARTIFACT wsi /bin/

docker:
    FROM alpine
    RUN apk add --no-cache gmp readline
    COPY +build/ /
    ENTRYPOINT ["/bin/wsdebug"]
    SAVE IMAGE wspace-corpus/c/ssiegl-wsdebug
