VERSION 0.8

build:
    FROM alpine
    WORKDIR /wsdebug
    RUN apk add --no-cache gcc musl-dev gmp-dev readline-static
    COPY wsdebug .
    RUN echo '#define VERSION "0.1"' > config.h && \
        gcc -O3 -static -DHAVE_CONFIG_H -I. -o wsdebug wsdebug.c debug.c fileio.c interprt.c storage.c -lgmp -lreadline && \
        gcc -O3 -static -DHAVE_CONFIG_H -I. -o wsi wsi.c fileio.c interprt.c storage.c -lgmp -lreadline
    SAVE ARTIFACT wsdebug /bin/
    SAVE ARTIFACT wsi /bin/
    SAVE ARTIFACT htdocs/*.ws /programs/
    SAVE IMAGE tmp

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wsdebug"]
    SAVE IMAGE wspace-corpus/c/ssiegl-wsdebug
