VERSION 0.8

build:
    # Fails to run Gradle on alpine due to javax.net.ssl.SSLHandshakeException
    FROM eclipse-temurin:8-jdk-jammy
    WORKDIR /kairos
    COPY kairos .
    RUN ./gradlew shadowJar
    SAVE ARTIFACT build/libs/kairos-1.0.0-all.jar /bin/kairos-1.0.0.jar
    SAVE ARTIFACT wsa_examples /programs/
    SAVE ARTIFACT wsa_functions /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /kairos
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/kairos-1.0.0.jar"]
    SAVE IMAGE wspace-corpus/java/vyo-kairos
