VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN gcc -O3 -g -static -o interpreter src/*.c
    SAVE ARTIFACT interpreter /bin/
    SAVE ARTIFACT ws/*.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/interpreter"]
    SAVE IMAGE wspace-corpus/c/cedricschwyter
