VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /Whitespace4j
    COPY Whitespace4j .
    RUN javac -d bin src/spp/Whitespace4j.java && \
        jar -cfe whitespace4j.jar spp.Whitespace4j -C bin .
    SAVE ARTIFACT whitespace4j.jar /bin/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /Whitespace4j
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespace4j.jar"]
    SAVE IMAGE wspace-corpus/java/brumbeere-whitespace4j
