VERSION 0.8

build:
    FROM coqorg/coq
    USER coq
    COPY --chown=coq wscoq /home/coq/wscoq
    WORKDIR /home/coq/wscoq
    # TODO: BUG? With Docker this can just be `make`, but Earthly seems to
    # require it to be run as a login shell.
    RUN sh -lc make
