VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    RUN apk add --no-cache apache-ant
    WORKDIR /whiteSpaceInterpreter
    COPY whiteSpaceInterpreter .
    RUN ant
    SAVE ARTIFACT dist/WhiteSpaceInterpreter.jar /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whiteSpaceInterpreter
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/WhiteSpaceInterpreter.jar"]
    SAVE IMAGE wspace-corpus/java/faurehu
