VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /go-wspace
    COPY go-wspace .
    RUN go mod init github.com/tempxla/go-wspace && \
        CGO_ENABLED=0 go build -o bin/go-wspace ./src
    # Tests fail
    # RUN go test ./...
    SAVE ARTIFACT bin/go-wspace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/go-wspace"]
    SAVE IMAGE wspace-corpus/go/tempxla-go-wspace
