VERSION 0.8

docker:
    FROM node:alpine
    WORKDIR /whitespace-lang-compiler
    COPY whitespace-lang-compiler .
    ENTRYPOINT ["node", "whitespacec"]
    SAVE IMAGE wspace-corpus/javascript/wdalmut
