VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    RUN apk add --no-cache curl
    WORKDIR /Whitespace-Compiler
    COPY Whitespace-Compiler .
    # whitespaceParser is manually modified, so a freshly-generated ANTLR parser
    # will not work:
    # java -jar antlr-4.5.2-complete.jar whitespace.g4
    RUN curl -O https://www.antlr.org/download/antlr-4.5.2-complete.jar && \
        \
        javac -cp antlr-4.5.2-complete.jar *.java && \
        \
        # Merge whitespaceCompiler and ANTLR jars: \
        mkdir tmp && \
        ( cd tmp \
          jar -xf ../antlr-4.5.2-complete.jar && \
          rm -rf META-INF && \
          cp ../*.class . && \
          jar -cfe ../whitespaceCompiler.jar LoadWhitespace . ) && \
        rm -rf tmp
    SAVE ARTIFACT whitespaceCompiler.jar /bin/
    SAVE ARTIFACT *.whitespace /programs/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /Whitespace-Compiler
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespaceCompiler.jar"]
    SAVE IMAGE wspace-corpus/java/wysang
