VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /whitespace_go
    COPY whitespace_go .
    RUN go test ./... && \
        CGO_ENABLED=0 go build -o releases/ws cmd/ws.go
    SAVE ARTIFACT releases/ws /bin/
    SAVE ARTIFACT samples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/ws"]
    SAVE IMAGE wspace-corpus/go/simomu
