VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Cupertino-WhiteSpace-Interperter
    COPY Cupertino-WhiteSpace-Interperter .
    RUN g++ -O3 -static -o whitespace src/*.cpp
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/cpp/frmsaul-cupertino
