VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /Whitespace_UnC
    COPY Whitespace_UnC .
    ENTRYPOINT ["python", "WhitespaceCompiler.py"]
    SAVE IMAGE wspace-corpus/python/ilikepython256-whitespace-unc
