VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /respace
    COPY respace .
    RUN make test
    RUN make LDFLAGS=-static
    SAVE ARTIFACT respace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/respace"]
    SAVE IMAGE wspace-corpus/cpp/thaliaarchi-respace
