VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /albino
    COPY albino .
    RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/albino /bin/
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/albino-run /bin/
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/albino-build /bin/
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/albino-exec /bin/
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/albino-gen /bin/
    SAVE ARTIFACT examples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/albino"]
    SAVE IMAGE wspace-corpus/rust/faultier-albino
