VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /SPOJ
    COPY SPOJ/wstp.cpp .
    RUN g++ -O3 -static -o wstp wstp.cpp
    SAVE ARTIFACT wstp /bin/
    SAVE ARTIFACT sbstr* /

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wstp"]
    SAVE IMAGE wspace-corpus/whitespace/t3nsor-spoj
