VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /wspacego
    COPY wspacego .
    RUN go mod init github.com/135yshr/wspacego && \
        go mod tidy && \
        CGO_ENABLED=0 go build
    # Tests fail
    # RUN go test ./...
    SAVE ARTIFACT wspacego /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/wspacego"]
    SAVE IMAGE wspace-corpus/go/135yshr-wspacego
