VERSION 0.8

docker:
    FROM python:2.7-alpine
    WORKDIR /abyad
    COPY abyad .
    RUN python generate_programs
    ENTRYPOINT ["python", "-m", "src"]
    SAVE IMAGE wspace-corpus/python/kareeeeem-abyad
