VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /whitespace
    COPY Codewars-algorithms/Solutions/whitespace_cw.py .
    ENTRYPOINT ["python", "whitespace_cw.py"]
    SAVE IMAGE wspace-corpus/python/ericpwilliamson-codewars
