VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    RUN apk add --no-cache apache-ant
    WORKDIR /whitespace
    COPY whitespace .
    RUN ant all && \
        jar -cfe whitespace.jar org.codeberg.jbanana.whitespace.Whitespace -C classes .
    COPY run.sh .
    SAVE ARTIFACT whitespace.jar /bin/
    SAVE ARTIFACT run.sh /bin/
    SAVE ARTIFACT examples /programs/examples
    SAVE ARTIFACT wstests /programs/wstests

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whitespace
    COPY +build/ .
    ENTRYPOINT ["bin/run.sh"]
    SAVE IMAGE wspace-corpus/java/jbanana
