VERSION 0.8

build:
    FROM clojure:temurin-21-lein-alpine
    WORKDIR /erasure
    COPY erasure .
    RUN lein uberjar
    SAVE ARTIFACT target/uberjar/erasure-2.0-standalone.jar bin//erasure-2.0.jar
    SAVE ARTIFACT resources /programs

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /erasure
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/erasure-2.0.jar"]
    SAVE IMAGE wspace-corpus/clojure/jmesyou-erasure
