VERSION 0.8

build:
    # Fails to run Gradle on alpine due to javax.net.ssl.SSLHandshakeException
    FROM eclipse-temurin:8-jdk-jammy
    RUN apt-get update && \
        apt-get install -y --no-install-recommends patch && \
        rm -rf /var/lib/apt/lists/*
    WORKDIR /space
    COPY space jar.patch ./
    RUN patch -p1 -i jar.patch && \
        ./gradlew jar
    SAVE ARTIFACT build/libs/space.jar /bin/
    SAVE ARTIFACT src/test/resources /programs

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /space
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/space.jar"]
    SAVE IMAGE wspace-corpus/kotlin/ze-space
