VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /whitespace
    COPY whitespace .
    RUN go mod init github.com/wspace/qeedquan-go && \
        CGO_ENABLED=0 go build -o whitespace
    SAVE ARTIFACT whitespace /bin/
    SAVE ARTIFACT *.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/go/qeedquan
