VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make gcc musl-dev
    WORKDIR /blacktime
    COPY blacktime .
    RUN make
    SAVE ARTIFACT blacktime /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/blacktime"]
    SAVE IMAGE wspace-corpus/c/threeifbywhiskey-blacktime
