VERSION 0.8

docker:
    FROM ruby:3-alpine
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    ENTRYPOINT ["ruby", "whitespace.rb"]
    SAVE IMAGE wspace-corpus/ruby/shimpeisaito
