VERSION 0.8

build:
    FROM eclipse-temurin:21-jdk-alpine
    WORKDIR /Whitespace
    COPY Whitespace .
    RUN javac -d bin $(find src -name '*.java') && \
        jar -cfe whitespace.jar at.yawk.whitspace.Whitespace -C bin .
    SAVE ARTIFACT whitespace.jar /bin/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /Whitespace
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespace.jar"]
    SAVE IMAGE wspace-corpus/java/yawkat
