VERSION 0.8

build:
    FROM mono
    WORKDIR /Whitespace
    COPY Whitespace .
    RUN msbuild -p:Configuration=Release
    SAVE ARTIFACT bin/Release/Whitespace.exe /bin/

docker:
    FROM mono:slim
    WORKDIR /Whitespace
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/Whitespace.exe"]
    SAVE IMAGE wspace-corpus/csharp/meeees
