VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++ gmp-dev
    WORKDIR /esco
    COPY esco .
    RUN ./configure && make
    SAVE ARTIFACT src/esco /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/esco"]
    SAVE IMAGE wspace-corpus/cpp/esco
