VERSION 0.8

build:
    FROM maven:3-eclipse-temurin-21-alpine
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN mvn -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 test package
    SAVE ARTIFACT target/whitespace-interpreter-1.0-SNAPSHOT.jar /bin/

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whitespace-interpreter
    COPY +build/ .
    # Needs Codewars entrypoint
    ENTRYPOINT ["java", "-jar", "bin/whitespace-interpreter-1.0-SNAPSHOT.jar"]
    SAVE IMAGE wspace-corpus/java/wrotycz
