VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make gcc musl-dev
    WORKDIR /txt2ws
    COPY txt2ws .
    RUN gcc -O3 -g -static -o txt2ws txt2ws.c
    SAVE ARTIFACT txt2ws /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/txt2ws"]
    SAVE IMAGE wspace-corpus/c/rispoli-txt2ws
