VERSION 0.8

docker:
    FROM node:alpine
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    ENTRYPOINT ["node", "whitespace.js"]
    SAVE IMAGE wspace-corpus/javascript/kanra1412
