VERSION 0.8

build:
    FROM scratch
    COPY whitespace-interpreter .
    SAVE ARTIFACT whitespace.js /bin/
    SAVE ARTIFACT test /programs

docker:
    FROM node:alpine
    WORKDIR /whitespace-interpreter
    COPY +build/ .
    ENTRYPOINT ["node", "bin/whitespace.js"]
    SAVE IMAGE wspace-corpus/javascript/kanra1412
