VERSION 0.8

whitespace-rs:
    FROM wspace-corpus/rust/censoredusername-whitespace-rs

build:
    FROM alpine
    RUN apk add --no-cache git make bash coreutils
    COPY --from=whitespace-rs /wsc /usr/local/bin/
    RUN git clone https://github.com/thaliaarchi/wslib
    WORKDIR /ws-challenges
    COPY ws-challenges .
    RUN make -k COMPILED_PROGRAMS= all run_tests || :
    RUN ./test.bash
    SAVE IMAGE wspace-corpus/whitespace/thaliaarchi-challenges
