VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /wsintercpp
    COPY wsintercpp .
    RUN g++ -O3 -static -o inter inter.cpp
    SAVE ARTIFACT inter /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/inter"]
    SAVE IMAGE wspace-corpus/cpp/burghard-wsintercpp
