VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /WhitespaceVM
    COPY WhitespaceVM .
    RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/whitespace-vm /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace-vm"]
    SAVE IMAGE wspace-corpus/rust/nareshganduri
