VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /ws
    COPY ws .
    RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/ws /bin/
    SAVE ARTIFACT examples/*.ws /programs/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/ws"]
    SAVE IMAGE wspace-corpus/rust/hamidrezakp
