VERSION 0.8

build:
    FROM mono
    WORKDIR /DotNot
    COPY DotNot .
    RUN nuget restore
    WORKDIR /DotNot/src/Whitespace.TestProject
    # TODO: Build fails: CSharpGeneratorDriver does not contain a constructor
    # that takes 3 arguments
    RUN msbuild -p:Configuration=Release
