VERSION 0.8

build:
    FROM mono
    WORKDIR /DotNot
    COPY DotNot .
    RUN nuget restore
    WORKDIR /DotNot/src/Whitespace.TestProject
    RUN msbuild -p:Configuration=Release

docker:
    SAVE IMAGE wspace-corpus/csharp/ryzngard-dotnot
