VERSION 0.8

build:
    FROM mono
    RUN apt-get update && \
        apt-get install -y --no-install-recommends \
            make gcc libc-dev flex bison && \
        rm -rf /var/lib/apt/lists/*
    WORKDIR /spacesharp
    COPY spacesharp .
    RUN make MCS=mcs
    SAVE ARTIFACT wsc.exe /bin/
    SAVE ARTIFACT libwsp.dll /bin/
    SAVE ARTIFACT tests/ws /programs

docker:
    # Requires full mono, not mono:slim, for the mono compiler
    FROM mono
    WORKDIR /spacesharp
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/wsc.exe"]
    SAVE IMAGE wspace-corpus/csharp/nicolasff-spacesharp
