VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitespace-compiler
    COPY Whitespace-compiler .
    RUN g++ -O3 -static -o pre pre.cpp
    SAVE ARTIFACT pre /bin/
    SAVE ARTIFACT wsc.sh /bin/
    SAVE ARTIFACT a.txt /bin/
    SAVE ARTIFACT c.txt /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/pre"]
    SAVE IMAGE wspace-corpus/cpp/kapustaikwas27
