VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitespace-compiler
    COPY Whitespace-compiler .
    RUN g++ -O3 -static -o pre pre.cpp
    SAVE ARTIFACT pre /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/pre"]
    SAVE IMAGE wspace-corpus/cpp/kapustaikwas27
