VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++ gmp-dev
    WORKDIR /ws
    COPY ws .
    RUN make CC='g++ -static'
    SAVE ARTIFACT ws /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/ws"]
    SAVE IMAGE wspace-corpus/cpp/knmorgan
