VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /whitespace-rs
    COPY esolangs/whitespace-rs .
    RUN cargo test && \
        RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu/release/whitespace-rs /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace-rs"]
    SAVE IMAGE wspace-corpus/rust/guricerin
