VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace
    COPY whitespace .
    # TODO: Build fails
    RUN g++ -std=c++11 -O3 -static -o whitespace whitespace.cpp
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/cpp/ricardoluis0
