VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /whitespace-go
    COPY whitespace-go .
    RUN CGO_ENABLED=0 go build
    SAVE ARTIFACT whitespace-go /bin/
    SAVE ARTIFACT examples /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace-go"]
    SAVE IMAGE wspace-corpus/go/samuelpratt
