VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache gcc musl-dev
    WORKDIR /I_C_Whitespace
    COPY I_C_Whitespace .
    RUN gcc -O3 -g -static -std=c99 -o whitespace *.c
    SAVE ARTIFACT whitespace /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whitespace"]
    SAVE IMAGE wspace-corpus/c/strangepan-i-c-whitespace
