VERSION 0.8

build:
    FROM rust:1.76
    WORKDIR /rustws
    COPY rustws .
    RUN cargo test
    # TODO: wsconvert.py
    SAVE ARTIFACT test.ws /programs/
    SAVE ARTIFACT test.wsv /programs/

docker:
    SAVE IMAGE wspace-corpus/rust/luminighty
