VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /WHINT
    COPY WHINT .
    RUN g++ -O3 -static -o whint whint.cpp
    SAVE ARTIFACT whint /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/whint"]
    SAVE IMAGE wspace-corpus/cpp/nullflagblues-whint
