VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /whitespace-programs
    COPY whitespace-programs .
    ENTRYPOINT ["python", "assemble.py"]
    SAVE IMAGE wspace-corpus/whitespace/drebelsky-programs
