VERSION 0.8

docker:
    FROM ruby:3-alpine
    WORKDIR /quine-relay
    COPY quine-relay/vendor/whitespace.rb .
    ENTRYPOINT ["ruby", "whitespace.rb"]
    SAVE IMAGE wspace-corpus/ruby/mame-quine-relay
