VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /gows
    COPY gows .
    RUN go mod init github.com/pocke/gows && \
        go mod tidy && \
        CGO_ENABLED=0 go build
    SAVE ARTIFACT gows /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/gows"]
    SAVE IMAGE wspace-corpus/go/pocke-gows
