VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN g++ -O3 -static -o WhitespaceInterpreter.out *.cpp
    SAVE ARTIFACT WhitespaceInterpreter.out /bin/
    SAVE ARTIFACT SamplePrograms /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/WhitespaceInterpreter.out"]
    SAVE IMAGE wspace-corpus/cpp/benajmin
