VERSION 0.8

docker:
    FROM ruby:3-alpine
    WORKDIR /whitespace
    COPY whitespace .
    # whitespace, whitespace-asm, or whitespace-disassem
    ENTRYPOINT ["ruby"]
    SAVE IMAGE wspace-corpus/ruby/wconrad
