VERSION 0.8

build:
    FROM mono
    WORKDIR /WhitespaceInterpreter
    COPY projectOne/The-Code/WhitespaceInterpreter .
    RUN msbuild -p:Configuration=Release
    SAVE ARTIFACT bin/Release/WhitespaceInterpreter.exe /bin/

docker:
    FROM mono:slim
    WORKDIR /WhitespaceInterpreter
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/WhitespaceInterpreter.exe"]
    SAVE IMAGE wspace-corpus/csharp/north15-projectone
