VERSION 0.8

# TODO: lci should be installed as a system dependency in the joined image
build-lci:
    FROM alpine
    RUN apk add --no-cache cmake make gcc g++ readline-dev
    GIT CLONE --branch=future https://github.com/justinmeza/lci /lci
    WORKDIR /lci
    RUN cmake . && \
        make
    # Tests fail
    # RUN ctest
    SAVE ARTIFACT lci /

build:
    FROM scratch
    COPY lolcode run.bash ./
    COPY +build-lci/lci .
    SAVE ARTIFACT *.lol /bin/
    SAVE ARTIFACT lci /bin/
    SAVE ARTIFACT run.bash /bin/
    SAVE ARTIFACT *.ws /programs/
    SAVE ARTIFACT *.b /programs/

docker:
    FROM alpine
    RUN apk add --no-cache bash readline-dev
    COPY +build/ /lolcode
    WORKDIR /lolcode/bin
    RUN mv lci /usr/local/bin/
    ENTRYPOINT ["./run.bash"]
    SAVE IMAGE wspace-corpus/lolcode/0x0dea
