VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache git cmake make gcc g++ readline-dev
    RUN git clone https://github.com/justinmeza/lci --branch=future
    WORKDIR /lci
    RUN cmake .
    RUN make
    # RUN ctest
    SAVE ARTIFACT lci /usr/local/bin/
    SAVE ARTIFACT *.lol /
    SAVE ARTIFACT *.ws /programs/
    SAVE ARTIFACT *.b /
    SAVE ARTIFACT run.bash /bin/

docker:
    FROM alpine
    RUN apk add --no-cache bash readline-dev
    WORKDIR /lolcode
    COPY +build/ .
    ENTRYPOINT ["bin/run.bash"]
    SAVE IMAGE wspace-corpus/lolcode/0x0dea
