VERSION 0.8

build:
    FROM golang:1.22
    WORKDIR /nebula
    COPY nebula .
    # TODO: Requires LLVM
    RUN go mod init github.com/thaliaarchi/nebula && \
        go mod tidy && \
        go test ./... && \
        go build
    SAVE ARTIFACT nebula /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/nebula"]
    SAVE IMAGE wspace-corpus/go/thaliaarchi-nebula
