VERSION 0.8

docker:
    FROM python:3-alpine
    RUN apk add --no-cache make g++ gmp-dev
    RUN pip install -v z3-solver
    WORKDIR /whitesymex
    COPY whitesymex .
    ENTRYPOINT ["python", "-m", "whitesymex.cli"]
    SAVE IMAGE wspace-corpus/python/umutoztunc-whitesymex
