VERSION 0.8

build:
    FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.1_12_1.9.8_3.3.1
    WORKDIR /whitespace-interpreter
    COPY whitespace-interpreter .
    RUN mkdir project && \
        echo 'addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.1.5")' > project/plugins.sbt && \
        sbt assembly
    SAVE ARTIFACT ["target/scala-2.11/Whitespace Interpreter-assembly-1.0.jar", "whitespace.jar"]
    SAVE ARTIFACT conf conf

docker:
    FROM eclipse-temurin:21-jre-alpine
    WORKDIR /whitespace-interpreter
    COPY +build/ .
    ENTRYPOINT ["java", "-jar", "bin/whitespace.jar"]
    SAVE IMAGE wspace-corpus/scala/stephenpatrick
