VERSION 0.8

build:
    FROM mono
    WORKDIR /WhiteSpaceInterpreter
    COPY WhiteSpaceInterpreter .
    WORKDIR /WhiteSpaceInterpreter/WhiteSpaceInterpretator
    RUN msbuild -p:Configuration=Release
    # TODO: Build fails: Mono does not implement WPF APIs
    SAVE ARTIFACT WhiteSpaceInterpretator/bin/Release/WhiteSpaceInterpretator.exe /bin/

docker:
    FROM mono:slim
    WORKDIR /WhiteSpaceInterpreter
    COPY +build/ .
    ENTRYPOINT ["mono", "bin/WhiteSpaceInterpretator.exe"]
    SAVE IMAGE wspace-corpus/csharp/reflash
