VERSION 0.8

build:
    FROM python:3.7-alpine
    WORKDIR /whitepy
    COPY whitepy .
    RUN pip install -r requirements.txt
    ENTRYPOINT ["python", "whitepycli"]

docker:
    SAVE IMAGE wspace-corpus/python/yasn77-whitepy
