VERSION 0.8

build:
    FROM node:alpine
    WORKDIR /wsa
    COPY wsa .
    RUN npm install && \
        npm run build
    SAVE ARTIFACT dist /bin/
    SAVE ARTIFACT node_modules /bin/
    SAVE ARTIFACT package.json /bin/
    SAVE ARTIFACT src/wsa/lib /programs/
    SAVE ARTIFACT wsa-tests /programs/
    SAVE ARTIFACT playground.wsa /programs/

docker:
    FROM node:alpine
    WORKDIR /wsa
    COPY +build/ .
    ENTRYPOINT ["node", "bin/dist/cli.js"]
    SAVE IMAGE wspace-corpus/typescript/voliva-wsa
