VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /whitespace_transpiler
    COPY whitespace_transpiler .
    ENTRYPOINT ["python", "transpiler.py"]
    SAVE IMAGE wspace-corpus/python/lachlancourt
