VERSION 0.8

docker:
    FROM perl:slim
    RUN cpanm Acme::Bleach
    WORKDIR /madness
    COPY madness .
    ENTRYPOINT ["perl", "whitespace_bleached.pl"]
    SAVE IMAGE wspace-corpus/perl/skabob42-madness
