VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++ ruby
    WORKDIR /nospace
    COPY nospace .
    RUN make release CXXFLAGS='-O3 -static'
    RUN ./test.rb
    SAVE ARTIFACT maicomp /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/maicomp"]
    SAVE IMAGE wspace-corpus/cpp/buyoh-nospace
