VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++ ruby
    WORKDIR /nospace
    COPY nospace .
    RUN make maicomp CXXFLAGS='-O3 -static'
    RUN ./test.rb
    SAVE ARTIFACT maicomp /bin/
    SAVE ARTIFACT vm /bin
    SAVE ARTIFACT test /programs

docker:
    FROM alpine
    RUN apk add --no-cache ruby
    WORKDIR /nospace
    COPY +build/ .
    ENTRYPOINT ["bin/maicomp"]
    SAVE IMAGE wspace-corpus/cpp/buyoh-nospace
