VERSION 0.8

build:
    FROM erlang
    WORKDIR /mrwhite
    COPY mrwhite .
    COPY mrwhite.erl src/
    RUN erl -noshell \
            -s leex file priv/from_text_lexer \
            -s yecc file priv/from_text_parser \
            -s leex file priv/from_whitespace_lexer \
            -s yecc file priv/from_whitespace_parser \
            -s erlang halt && \
        mv priv/*.erl src/
    RUN rebar3 compile
    RUN rebar3 eunit
    COPY run.sh .
    SAVE ARTIFACT _build/default/lib/mrwhite/ebin /bin
    SAVE ARTIFACT run.sh /bin/
    SAVE ARTIFACT priv/sample /programs

docker:
    FROM erlang
    WORKDIR /mrwhite
    COPY +build/ .
    ENTRYPOINT ["bin/run.sh"]
    SAVE IMAGE wspace-corpus/erlang/derek121-mrwhite
