VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache g++
    WORKDIR /Whitespace-Interpreter
    COPY Whitespace-Interpreter .
    RUN g++ -O3 -static -o ws Lexer.cc Parser.cc
    SAVE ARTIFACT ws /bin/
    SAVE ARTIFACT WsFiles /programs

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/ws"]
    SAVE IMAGE wspace-corpus/cpp/noia1
