VERSION 0.8

build:
    FROM alpine
    RUN apk add --no-cache make g++
    WORKDIR /ws-interpreter
    COPY ws-interpreter .
    RUN mkdir bin
    RUN make -C src TARGET=../bin/ws CXX='g++ -static'
    SAVE ARTIFACT bin/ws /bin/

docker:
    FROM scratch
    COPY +build/ /
    ENTRYPOINT ["/bin/ws"]
    SAVE IMAGE wspace-corpus/cpp/yuukiaria
