VERSION 0.8

docker:
    FROM python:3-alpine
    WORKDIR /AdventOfCode2022.ws
    COPY AdventOfCode2022.ws .
    ENTRYPOINT ["python", "main.py"]
    SAVE IMAGE wspace-corpus/whitespace/lukepebody-advent-of-code
