VERSION 0.8

docker:
    FROM node:alpine
    WORKDIR /whitespace-lang
    COPY whitespace-lang .
    RUN npm install
    ENTRYPOINT ["node", "index.js"]
    SAVE IMAGE wspace-corpus/javascript/loklaan-whitespace-lang
