VERSION 0.8

build:
    FROM node:alpine
    WORKDIR /whitespace-lang
    COPY whitespace-lang .
    RUN npm install
    SAVE ARTIFACT index.js /bin/
    SAVE ARTIFACT lib /bin/
    SAVE ARTIFACT node_modules /bin/
    SAVE ARTIFACT package.json /bin/
    SAVE ARTIFACT tests.ws /programs/

docker:
    FROM node:alpine
    WORKDIR /whitespace-lang
    COPY +build/ .
    ENTRYPOINT ["node", "bin/index.js"]
    SAVE IMAGE wspace-corpus/javascript/loklaan-whitespace-lang
